import type {
  Doctor, Facility, Specialty, VisitingSession, Scheme,
  LabTest, Procedure, MedicalTerm, HealthAlert, HealthUpdate,
  Service, UserReport, VerificationRecord, AuditLog, AdminUser,
} from "@/types"

export const DEMO_SPECIALTIES: Specialty[] = [
  { id: "s1", name_en: "General Physician", name_mr: "सामान्य चिकित्सक" },
  { id: "s2", name_en: "Cardiologist", name_mr: "हृदयरोग तज्ज्ञ" },
  { id: "s3", name_en: "Pediatrician", name_mr: "बालरोग तज्ज्ञ" },
  { id: "s4", name_en: "Gynecologist", name_mr: "स्त्रीरोग तज्ज्ञ" },
  { id: "s5", name_en: "Orthopedic", name_mr: "हाडरोग तज्ज्ञ" },
  { id: "s6", name_en: "Dermatologist", name_mr: "त्वचारोग तज्ज्ञ" },
  { id: "s7", name_en: "ENT Specialist", name_mr: "कान-नाक-घशाचे तज्ज्ञ" },
  { id: "s8", name_en: "Ophthalmologist", name_mr: "नेत्र तज्ज्ञ" },
  { id: "s9", name_en: "Psychiatrist", name_mr: "मानसोपचार तज्ज्ञ" },
  { id: "s10", name_en: "Dentist", name_mr: "दंत तज्ज्ञ" },
]

export const DEMO_FACILITIES: Facility[] = [
  {
    id: "f1", slug: "pandharkawda-civil-hospital",
    name_en: "Pandharkawda Civil Hospital",
    name_mr: "पांढरकवडा सिव्हिल हॉस्पिटल",
    type: "government",
    address_en: "Main Road, Pandharkawda, Yavatmal, Maharashtra 445302",
    address_mr: "मुख्य रस्ता, पांढरकवडा, यवतमाळ, महाराष्ट्र 445302",
    phone: "0000000000",
    lat: 20.2861, lng: 78.9312,
    services_en: ["Emergency", "Outpatient", "Maternity", "Immunization", "Malnutrition Treatment", "De-addiction"],
    services_mr: ["आपत्कालीन", "बाह्यरुग्ण", "प्रसूती", "लसीकरण", "कुपोषण उपचार", "व्यसनमुक्ती"],
    is_public_hospital: true, has_emergency: true, verified: true,
    last_verified: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "f2", slug: "shree-medical-centre",
    name_en: "Shree Medical Centre",
    name_mr: "श्री मेडिकल सेंटर",
    type: "clinic",
    address_en: "Station Road, Near Bus Stand, Pandharkawda",
    address_mr: "स्टेशन रोड, बस स्थानकाजवळ, पांढरकवडा",
    phone: "0000000000",
    lat: 20.2855, lng: 78.9301,
    services_en: ["General Consultation", "Pediatrics", "Pharmacy"],
    services_mr: ["सामान्य सल्ला", "बालरोग", "फार्मसी"],
    is_public_hospital: false, has_emergency: false, verified: true,
    last_verified: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "f3", slug: "city-care-clinic",
    name_en: "City Care Clinic",
    name_mr: "सिटी केअर क्लिनिक",
    type: "clinic",
    address_en: "Civil Lines, Pandharkawda",
    address_mr: "सिव्हिल लाईन्स, पांढरकवडा",
    phone: "0000000000",
    lat: 20.2870, lng: 78.9320,
    services_en: ["General Consultation", "Minor Procedures"],
    services_mr: ["सामान्य सल्ला", "किरकोळ प्रक्रिया"],
    is_public_hospital: false, has_emergency: false, verified: true,
    last_verified: new Date(Date.now() - 18 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "f4", slug: "lifeline-diagnostic-centre",
    name_en: "Lifeline Diagnostic Centre",
    name_mr: "लाईफलाईन डायग्नोस्टिक सेंटर",
    type: "diagnostic",
    address_en: "Market Yard Road, Pandharkawda",
    address_mr: "मार्केट यार्ड रोड, पांढरकवडा",
    phone: "0000000000",
    lat: 20.2840, lng: 78.9290,
    services_en: ["Blood Tests", "X-Ray", "Ultrasound", "ECG"],
    services_mr: ["रक्त तपासण्या", "एक्स-रे", "अल्ट्रासाऊंड", "इसीजी"],
    is_public_hospital: false, has_emergency: false, verified: true,
    last_verified: new Date(Date.now() - 8 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "f5", slug: "pandharkawda-medical-centre",
    name_en: "Pandharkawda Medical Centre",
    name_mr: "पांढरकवडा मेडिकल सेंटर",
    type: "clinic",
    address_en: "Hospital Road, Pandharkawda",
    address_mr: "हॉस्पिटल रोड, पांढरकवडा",
    phone: "0000000000",
    lat: 20.2865, lng: 78.9310,
    services_en: ["General Consultation", "Cardiology Visits", "Orthopedic Visits", "Pharmacy"],
    services_mr: ["सामान्य सल्ला", "हृदयरोग भेटी", "हाडरोग भेटी", "फार्मसी"],
    is_public_hospital: false, has_emergency: false, verified: true,
    last_verified: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
]

export const DEMO_DOCTORS: Doctor[] = [
  {
    id: "d1", slug: "dr-anil-deshmukh",
    name_en: "Dr. Anil Deshmukh",
    name_mr: "डॉ. अनिल देशमुख",
    qualification_en: "MBBS, MD (Medicine)",
    qualification_mr: "एमबीबीएस, एमडी (मेडिसिन)",
    specialty_id: "s1", specialty: DEMO_SPECIALTIES[0],
    is_visiting: false, home_city_en: null, home_city_mr: null,
    facility_id: "f2", facility: DEMO_FACILITIES[1],
    phone: "0000000000", verified: true,
    last_verified: new Date(Date.now() - 2 * 86400000).toISOString(),
    publication_consent: true, created_at: new Date().toISOString(),
  },
  {
    id: "d2", slug: "dr-sunita-jadhav",
    name_en: "Dr. Sunita Jadhav",
    name_mr: "डॉ. सुनिता जाधव",
    qualification_en: "MBBS, DCH",
    qualification_mr: "एमबीबीएस, डीसीएच",
    specialty_id: "s3", specialty: DEMO_SPECIALTIES[2],
    is_visiting: false, home_city_en: null, home_city_mr: null,
    facility_id: "f2", facility: DEMO_FACILITIES[1],
    phone: "0000000000", verified: true,
    last_verified: new Date(Date.now() - 5 * 86400000).toISOString(),
    publication_consent: true, created_at: new Date().toISOString(),
  },
  {
    id: "d3", slug: "dr-rajesh-patil",
    name_en: "Dr. Rajesh Patil",
    name_mr: "डॉ. राजेश पाटील",
    qualification_en: "MBBS, MD (Pediatrics)",
    qualification_mr: "एमबीबीएस, एमडी (बालरोग)",
    specialty_id: "s3", specialty: DEMO_SPECIALTIES[2],
    is_visiting: false, home_city_en: null, home_city_mr: null,
    facility_id: "f3", facility: DEMO_FACILITIES[2],
    phone: "0000000000", verified: true,
    last_verified: new Date(Date.now() - 18 * 86400000).toISOString(),
    publication_consent: true, created_at: new Date().toISOString(),
  },
  {
    id: "d4", slug: "dr-priya-sharma",
    name_en: "Dr. Priya Sharma",
    name_mr: "डॉ. प्रिया शर्मा",
    qualification_en: "MBBS, MD (Cardiology)",
    qualification_mr: "एमबीबीएस, एमडी (हृदयरोग)",
    specialty_id: "s2", specialty: DEMO_SPECIALTIES[1],
    is_visiting: true, home_city_en: "Nagpur", home_city_mr: "नागपूर",
    facility_id: "f5", facility: DEMO_FACILITIES[4],
    phone: "0000000000", verified: true,
    last_verified: new Date(Date.now() - 3 * 86400000).toISOString(),
    publication_consent: true, created_at: new Date().toISOString(),
  },
  {
    id: "d5", slug: "dr-mahesh-kulkarni",
    name_en: "Dr. Mahesh Kulkarni",
    name_mr: "डॉ. महेश कुलकर्णी",
    qualification_en: "MS (Orthopedics)",
    qualification_mr: "एमएस (हाडरोग)",
    specialty_id: "s5", specialty: DEMO_SPECIALTIES[4],
    is_visiting: true, home_city_en: "Amravati", home_city_mr: "अमरावती",
    facility_id: "f5", facility: DEMO_FACILITIES[4],
    phone: "0000000000", verified: true,
    last_verified: new Date(Date.now() - 1 * 86400000).toISOString(),
    publication_consent: true, created_at: new Date().toISOString(),
  },
  {
    id: "d6", slug: "dr-nisha-gawande",
    name_en: "Dr. Nisha Gawande",
    name_mr: "डॉ. निशा गवांडे",
    qualification_en: "MBBS, MS (Gynecology)",
    qualification_mr: "एमबीबीएस, एमएस (स्त्रीरोग)",
    specialty_id: "s4", specialty: DEMO_SPECIALTIES[3],
    is_visiting: false, home_city_en: null, home_city_mr: null,
    facility_id: "f1", facility: DEMO_FACILITIES[0],
    phone: "0000000000", verified: true,
    last_verified: new Date(Date.now() - 4 * 86400000).toISOString(),
    publication_consent: true, created_at: new Date().toISOString(),
  },
  {
    id: "d7", slug: "dr-sandeep-bhagwat",
    name_en: "Dr. Sandeep Bhagwat",
    name_mr: "डॉ. संदीप भागवत",
    qualification_en: "MBBS, DVD (Dermatology)",
    qualification_mr: "एमबीबीएस, डीव्हीडी (त्वचारोग)",
    specialty_id: "s6", specialty: DEMO_SPECIALTIES[5],
    is_visiting: false, home_city_en: null, home_city_mr: null,
    facility_id: "f3", facility: DEMO_FACILITIES[2],
    phone: "0000000000", verified: true,
    last_verified: new Date(Date.now() - 15 * 86400000).toISOString(),
    publication_consent: true, created_at: new Date().toISOString(),
  },
]

const today = new Date()
const formatDate = (daysFromNow: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() + daysFromNow)
  return d.toISOString().split("T")[0]
}

export const DEMO_VISITING_SESSIONS: VisitingSession[] = [
  {
    id: "v1", doctor_id: "d4", doctor: DEMO_DOCTORS[3],
    facility_id: "f5", facility: DEMO_FACILITIES[4],
    visit_date: formatDate(16), start_time: "10:00", end_time: "14:00",
    status: "confirmed", confirmed_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "v2", doctor_id: "d5", doctor: DEMO_DOCTORS[4],
    facility_id: "f5", facility: DEMO_FACILITIES[4],
    visit_date: formatDate(3), start_time: "11:00", end_time: "15:00",
    status: "confirmed", confirmed_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "v3", doctor_id: "d4", doctor: DEMO_DOCTORS[3],
    facility_id: "f5", facility: DEMO_FACILITIES[4],
    visit_date: formatDate(30), start_time: "10:00", end_time: "14:00",
    status: "pending", confirmed_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "v4", doctor_id: "d5", doctor: DEMO_DOCTORS[4],
    facility_id: "f5", facility: DEMO_FACILITIES[4],
    visit_date: formatDate(45), start_time: "11:00", end_time: "15:00",
    status: "pending", confirmed_at: null,
    created_at: new Date().toISOString(),
  },
]

export const DEMO_SCHEMES: Scheme[] = [
  {
    id: "sc1", slug: "mahatma-jyotiba-phule-jan-arogya-yojana",
    title_en: "Mahatma Jyotiba Phule Jan Arogya Yojana",
    title_mr: "महात्मा ज्योतिबा फुले जन आरोग्य योजना",
    summary_en: "Health insurance scheme providing cashless treatment for specified procedures at empaneled hospitals.",
    summary_mr: "संलग्न रुग्णालयांमध्ये निर्दिष्ट प्रक्रियांसाठी कॅशलेस उपचार देणारी आरोग्य विमा योजना.",
    eligibility_en: "Families listed in the eligible beneficiary list, primarily from below-poverty-line categories.",
    eligibility_mr: "पात्र लाभार्थी यादीत समाविष्ट कुटुंबे, मुख्यतः गरिबी रेषेखालील गटातून.",
    benefits_en: "Coverage up to specified amounts per family per year for listed procedures including surgery, cardiology, and more.",
    benefits_mr: "शस्त्रक्रिया, हृदयरोग इत्यादींसह निर्दिष्ट प्रक्रियांसाठी प्रति कुटुंब प्रति वर्ष निर्दिष्ट रकमेपर्यंत कव्हर.",
    documents_en: ["Ration Card", "Aadhaar Card", "Beneficiary ID", "Income Certificate"],
    documents_mr: ["रेशन कार्ड", "आधार कार्ड", "लाभार्थी आयडी", "उत्पन्न प्रमाणपत्र"],
    official_url: "https://bjsa.gov.in",
    helpline: "1800-000-0000",
    source_en: "State Health Department, Maharashtra",
    source_mr: "राज्य आरोग्य विभाग, महाराष्ट्र",
    reviewed_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "sc2", slug: "chief-minister-baliraja-free-treatment-scheme",
    title_en: "Chief Minister Baliraja Free Treatment Scheme",
    title_mr: "मुख्यमंत्री बलीराजा मोफत उपचार योजना",
    summary_en: "Free treatment scheme for farmers and their families at government and empaneled private hospitals.",
    summary_mr: "सरकारी आणि संलग्न खाजगी रुग्णालयांमध्ये शेतकरी आणि त्यांच्या कुटुंबासाठी मोफत उपचार योजना.",
    eligibility_en: "Registered farmers with valid farmer registration certificate and their dependents.",
    eligibility_mr: "वैध शेतकरी नोंदणी प्रमाणपत्र असलेले शेतकरी आणि त्यांचे आश्रित.",
    benefits_en: "Free medical and surgical treatment up to specified amounts annually.",
    benefits_mr: "वार्षिक निर्दिष्ट रकमेपर्यंत मोफत वैद्यकीय आणि शस्त्रक्रिया उपचार.",
    documents_en: ["Farmer Registration Certificate", "Aadhaar Card", "Ration Card"],
    documents_mr: ["शेतकरी नोंदणी प्रमाणपत्र", "आधार कार्ड", "रेशन कार्ड"],
    official_url: "https://arogya.maharashtra.gov.in",
    helpline: "1800-111-2222",
    source_en: "Health Department, Government of Maharashtra",
    source_mr: "आरोग्य विभाग, महाराष्ट्र शासन",
    reviewed_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: "sc3", slug: "janani-shishu-suraksha-karyakram",
    title_en: "Janani Shishu Suraksha Karyakram",
    title_mr: "जननी शिशु सुरक्षा कार्यक्रम",
    summary_en: "Free institutional delivery and newborn care at government health facilities.",
    summary_mr: "सरकारी आरोग्य केंद्रांमध्ये मोफत संस्थात्मक प्रसूती आणि नवजात शिशूंची काळजी.",
    eligibility_en: "All pregnant women delivering at government health facilities.",
    eligibility_mr: "सरकारी आरोग्य केंद्रांमध्ये प्रसूती करणाऱ्या सर्व गर्भवती महिला.",
    benefits_en: "Free delivery, C-section, blood tests, medicines, and 7-day postnatal care.",
    benefits_mr: "मोफत प्रसूती, सिझेरियन, रक्त तपासण्या, औषधे, आणि 7 दिवसांची प्रसूतीनंतरची काळजी.",
    documents_en: ["Aadhaar Card", "BPL Card (if applicable)"],
    documents_mr: ["आधार कार्ड", "बीपीएल कार्ड (लागू असल्यास)"],
    official_url: "https://nhm.gov.in",
    helpline: "1800-180-1104",
    source_en: "National Health Mission",
    source_mr: "राष्ट्रीय आरोग्य मिशन",
    reviewed_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
]

export const DEMO_TESTS: LabTest[] = [
  {
    id: "t1", slug: "complete-blood-count",
    name_en: "Complete Blood Count (CBC)",
    name_mr: "संपूर्ण रक्त गणना (सीबीसी)",
    what_is_en: "A common blood test that evaluates overall health and detects a wide range of disorders including anemia, infection, and leukemia.",
    what_is_mr: "एक सामान्य रक्त तपासणी जी एकूण आरोग्य तपासते आणि रक्तक्षय, संक्रमण आणि रक्तकर्करोग यांसारख्या विविध विकारांचा शोध घेते.",
    why_ordered_en: "As part of a routine health checkup, to monitor a known condition, or to investigate symptoms like fatigue, fever, or weakness.",
    why_ordered_mr: "नियमित आरोग्य तपासणीचा भाग म्हणून, ज्ञात स्थितीचे निरीक्षण करण्यासाठी, किंवा थकवा, ताप, किंवा अशक्तपणासारखी लक्षणे तपासण्यासाठी.",
    preparation_en: "No special preparation is typically required. You can eat and drink normally before the test.",
    preparation_mr: "विशेष तयारी आवश्यक नाही. तपासणीपूर्वी सामान्यपणे खाऊ आणि पिऊ शकता.",
    fasting_required: false,
    duration_en: "A few minutes for the blood draw. Results may be available within a few hours to one day.",
    duration_mr: "रक्त काढण्यासाठी काही मिनिटे. निकाल काही तासांत ते एका दिवसात मिळू शकतात.",
    where_available_en: "Lifeline Diagnostic Centre, Pandharkawda Civil Hospital",
    where_available_mr: "लाईफलाईन डायग्नोस्टिक सेंटर, पांढरकवडा सिव्हिल हॉस्पिटल",
    reviewed_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "t2", slug: "blood-sugar-fasting",
    name_en: "Fasting Blood Sugar",
    name_mr: "उपवास रक्त साखर",
    what_is_en: "Measures the glucose level in your blood after fasting for at least 8 hours. Used to diagnose and monitor diabetes.",
    what_is_mr: "किमान 8 तास उपवास केल्यानंतर तुमच्या रक्तातील ग्लुकोज पातळी मोजते. मधुमेह निदान आणि निरीक्षणासाठी वापरले जाते.",
    why_ordered_en: "To screen for diabetes, monitor blood sugar levels in diabetic patients, or investigate symptoms of high/low blood sugar.",
    why_ordered_mr: "मधुमेहासाठी तपासणी, मधुमेह रुग्णांमध्ये रक्त साखर पातळीचे निरीक्षण, किंवा उच्च/कमी रक्त साखरेची लक्षणे तपासण्यासाठी.",
    preparation_en: "Fast for at least 8 hours before the test. Only water is permitted during fasting. Inform your doctor about any medications you are taking.",
    preparation_mr: "तपासणीपूर्वी किमान 8 तास उपवास करा. उपवासादरम्यान फक्त पाणी प्यायला परवानगी आहे. तुम्ही घेत असलेली औषधे डॉक्टरांना कळवा.",
    fasting_required: true,
    duration_en: "A few minutes for the blood draw. Results typically available within a few hours.",
    duration_mr: "रक्त काढण्यासाठी काही मिनिटे. निकाल साधारण काही तासांत मिळतात.",
    where_available_en: "Lifeline Diagnostic Centre, Shree Medical Centre",
    where_available_mr: "लाईफलाईन डायग्नोस्टिक सेंटर, श्री मेडिकल सेंटर",
    reviewed_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "t3", slug: "hba1c",
    name_en: "HbA1c (Glycated Hemoglobin)",
    name_mr: "एचबीए१सी (ग्लायकेटेड हिमोग्लोबिन)",
    what_is_en: "Measures average blood sugar levels over the past 2-3 months, showing how well diabetes is being managed.",
    what_is_mr: "गेल्या 2-3 महिन्यांतील सरासरी रक्त साखर पातळी मोजते, दर्शविते की मधुमेळ चांगल्या प्रकारे व्यवस्थापित होत आहे.",
    why_ordered_en: "To monitor long-term blood sugar control in diabetic patients or to help diagnose diabetes.",
    why_ordered_mr: "मधुमेह रुग्णांमध्ये दीर्घकाळाची रक्त साखर नियंत्रणाचे निरीक्षण करण्यासाठी किंवा मधुमेळ निदानास मदत करण्यासाठी.",
    preparation_en: "No fasting is required. You can eat and drink normally before this test.",
    preparation_mr: "उपवास आवश्यक नाही. या तपासणीपूर्वी सामान्यपणे खाऊ आणि पिऊ शकता.",
    fasting_required: false,
    duration_en: "A few minutes for the blood draw. Results may take 1-2 days.",
    duration_mr: "रक्त काढण्यासाठी काही मिनिटे. निकालासाठी 1-2 दिवस लागू शकतात.",
    where_available_en: "Lifeline Diagnostic Centre",
    where_available_mr: "लाईफलाईन डायग्नोस्टिक सेंटर",
    reviewed_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
]

export const DEMO_PROCEDURES: Procedure[] = [
  {
    id: "p1", slug: "x-ray",
    name_en: "X-Ray",
    name_mr: "एक्स-रे",
    what_is_en: "A quick, painless imaging test that uses small amounts of radiation to create pictures of the inside of the body.",
    what_is_mr: "एक त्वरित, वेदनारहित इमेजिंग तपासणी जी शरीराच्या आतील भागांचे चित्र तयार करण्यासाठी किरणोत्सर्गाचा वापर करते.",
    why_used_en: "To examine bones for fractures, detect lung conditions like pneumonia, or investigate certain internal structures.",
    why_used_mr: "हाडांचे फ्रॅक्चर तपासण्यासाठी, न्युमोनियासारख्या फुफ्फुसाच्या स्थितीचा शोध घेण्यासाठी, किंवा काही अंतर्गत संरचना तपासण्यासाठी.",
    what_happens_en: "You will be positioned between the X-ray machine and the detector. You need to stay still for a few seconds while the image is taken. Multiple views may be taken.",
    what_happens_mr: "तुम्हाला एक्स-रे मशीन आणि डिटेक्टर दरम्यान स्थित केले जाईल. चित्र घेत असताना काही सेकंद स्थिर राहणे आवश्यक आहे. एकाधिक दृश्ये घेतली जाऊ शकतात.",
    preparation_en: "Remove any metal objects (jewelry, watches) from the area being examined. Wear comfortable clothing.",
    preparation_mr: "तपास केल्या जाणाऱ्या भागातून कोणतेही धातूची वस्तू (दागिने, घड्याळ) काढा. आरामदायक कपडे घाला.",
    questions_to_ask_en: ["When will I get the results?", "Is there any special preparation needed?", "How soon can I resume normal activities?"],
    questions_to_ask_mr: ["निकाल कधी मिळतील?", "कोणती विशेष तयारी आवश्यक आहे का?", "मी पारंपारिक क्रिया कधी पुन्हा सुरू करू शकतो?"],
    where_available_en: "Lifeline Diagnostic Centre, Pandharkawda Civil Hospital",
    where_available_mr: "लाईफलाईन डायग्नोस्टिक सेंटर, पांढरकवडा सिव्हिल हॉस्पिटल",
    reviewed_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: "p2", slug: "ultrasound",
    name_en: "Ultrasound (Sonography)",
    name_mr: "अल्ट्रासाऊंड (सोनोग्राफी)",
    what_is_en: "An imaging test that uses sound waves to create real-time pictures of internal organs and structures without radiation.",
    what_is_mr: "एक इमेजिंग तपासणी जी किरणोत्सर्गाशिवाय आंतरिक अवयव आणि संरचनांचे रिअल-टाईम चित्र तयार करण्यासाठी ध्वनी लहरी वापरते.",
    why_used_en: "To examine the abdomen, monitor pregnancy, investigate pelvic issues, or guide certain procedures.",
    why_used_mr: "पोटाचा तपास, गर्भधारणेचे निरीक्षण, श्रोणिच्या समस्या तपासण्यासाठी, किंवा काही प्रक्रियांचे मार्गदर्शन करण्यासाठी.",
    what_happens_en: "Gel is applied to the skin and a transducer is moved over the area. The test is painless and typically takes 15-30 minutes.",
    what_happens_mr: "त्वचेवर जेल लावले जाते आणि ट्रान्सड्युसर भागावर हलवला जातो. तपासणी वेदनारहित आहे आणि साधारण 15-30 मिनिटे लागतात.",
    preparation_en: "For abdominal ultrasound, you may be asked to fast for 6-8 hours. For pelvic ultrasound, you may need a full bladder — drink water and do not urinate before the test.",
    preparation_mr: "पोटाच्या अल्ट्रासाऊंडसाठी, 6-8 तास उपवास करावा लागू शकतो. श्रोणिच्या अल्ट्रासाऊंडसाठी, मूत्राशय भरलेला असणे आवश्यक आहे — पाणी प्या आणि तपासणीपूर्वी मूत्र करू नका.",
    questions_to_ask_en: ["Do I need to fast?", "Should I have a full bladder?", "When will I get the results?"],
    questions_to_ask_mr: ["मला उपवास करावा लागेल का?", "माझे मूत्राशय भरलेले असावे का?", "निकाल कधी मिळतील?"],
    where_available_en: "Lifeline Diagnostic Centre",
    where_available_mr: "लाईफलाईन डायग्नोस्टिक सेंटर",
    reviewed_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "p3", slug: "mri",
    name_en: "MRI (Magnetic Resonance Imaging)",
    name_mr: "एमआरआय (मॅग्नेटिक रेझोनन्स इमेजिंग)",
    what_is_en: "A detailed imaging test that uses powerful magnets and radio waves to create detailed images of organs and tissues.",
    what_is_mr: "एक तपशीलवार इमेजिंग तपासणी जी अवयव आणि ऊतींचे तपशीलवार चित्र तयार करण्यासाठी शक्तिशाली चुंबक आणि रेडिओ लहरी वापरते.",
    why_used_en: "To examine the brain, spinal cord, joints, and soft tissues in great detail. Used for diagnosing tumors, injuries, and neurological conditions.",
    why_used_mr: "मेंदू, पाठीचा कणा, सांधे आणि मऊ ऊती तपासण्यासाठी तपशीलवार. ट्यूमर, दुखापती आणि तंत्रिका स्थितींचे निदानासाठी.",
    what_happens_en: "You lie inside a large tube-like machine for 30-60 minutes. It is important to stay very still. The machine makes loud tapping noises.",
    what_happens_mr: "तुम्ही 30-60 मिनिटे मोठ्या ट्यूबसारख्या मशीनमध्ये झोपता. अगदी स्थिर राहणे महत्त्वाचे आहे. मशीन मोठ्या टॅपिंग आवाज करते.",
    preparation_en: "Remove all metal objects. Inform the technician if you have any implants, pacemakers, or metal fragments. You may be offered earplugs.",
    preparation_mr: "सर्व धातूची वस्तू काढा. तुमच्याकडे कोणतेही इम्प्लांट, पेसमेकर किंवा धातूचे तुकडे असल्यास तंत्रज्ञाला कळवा. तुम्हाला इअरप्लग दिले जाऊ शकतात.",
    questions_to_ask_en: ["How long will it take?", "Can I have earplugs?", "Should I bring someone with me?", "Is it safe with my implants?"],
    questions_to_ask_mr: ["किती वेळ लागेल?", "मला इअरप्लग मिळू शकतात का?", "मी कोणाला सोबत आणावे का?", "माझ्या इम्प्लांटसह सुरक्षित आहे का?"],
    where_available_en: "Available at larger hospitals in Yavatmal (referral required)",
    where_available_mr: "यवतमाळमधील मोठ्या रुग्णालयांमध्ये उपलब्ध (संदर्भ आवश्यक)",
    reviewed_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
]

export const DEMO_MEDICAL_TERMS: MedicalTerm[] = [
  {
    id: "mt1", slug: "hba1c",
    term_en: "HbA1c",
    term_mr: "एचबीए१सी",
    meaning_en: "A blood test that shows your average blood sugar level over the past 2 to 3 months.",
    meaning_mr: "एक रक्त तपासणी जी गेल्या 2 ते 3 महिन्यांतील तुमची सरासरी रक्त साखर पातळी दर्शविते.",
    why_you_hear_en: "Doctors order this test to check how well diabetes is being managed over time.",
    why_you_hear_mr: "डॉक्टर ही तपासणी कालांतराने मधुमेळ किती चांगल्या प्रकारे व्यवस्थापित होत आहे याची तपासणी करण्यासाठी घेतात.",
    general_info_en: "A normal HbA1c level is below 5.7%. Levels between 5.7% and 6.4% indicate prediabetes, and 6.5% or above suggests diabetes. Target ranges may differ for individual patients.",
    general_info_mr: "सामान्य एचबीए१सी पातळी 5.7% च्या खाली आहे. 5.7% ते 6.4% दरम्यानच्या पातळी प्रीडायबिटीज दर्शवितात, आणि 6.5% किंवा त्यापुढे मधुमेळ सूचित करते. लक्ष्य श्रेणी वैयक्तिक रुग्णांसाठी भिन्न असू शकतात.",
    source_en: "Mayo Clinic, National Institute of Health",
    source_mr: "मेयो क्लिनिक, नॅशनल इंस्टिट्यूट ऑफ हेल्थ",
    reviewed_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: "mt2", slug: "bp-blood-pressure",
    term_en: "Blood Pressure (BP)",
    term_mr: "रक्तदाब (बीपी)",
    meaning_en: "The force of blood pushing against the walls of your arteries as your heart pumps blood.",
    meaning_mr: "तुमचे हृदय रक्त पंप करत असताना तुमच्या धमन्यांच्या भिंतींवर रक्त ढकलण्याचे बल.",
    why_you_hear_en: "Measured during most checkups to screen for hypertension (high blood pressure) or hypotension (low blood pressure).",
    why_you_hear_mr: "उच्च रक्तदाब किंवा कमी रक्तदाब तपासण्यासाठी बहुतांश तपासण्यांमध्ये मोजले जाते.",
    general_info_en: "Normal BP is around 120/80 mmHg. Readings consistently above 140/90 may indicate hypertension. Low BP is generally below 90/60. Always discuss your readings with your doctor.",
    general_info_mr: "सामान्य बीपी सुमारे 120/80 mmHg आहे. सातत्याने 140/90 पेक्षा जास्त रीडिंग उच्च रक्तदाब दर्शवू शकतात. कमी बीपी साधारण 90/60 खाली असते. तुमची रीडिंग नेहमी डॉक्टरांसोबत चर्चा करा.",
    source_en: "American Heart Association, WHO",
    source_mr: "अमेरिकन हार्ट असोसिएशन, डब्ल्यूएचओ",
    reviewed_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "mt3", slug: "cbc",
    term_en: "CBC (Complete Blood Count)",
    term_mr: "सीबीसी (संपूर्ण रक्त गणना)",
    meaning_en: "A blood test that measures the number and types of cells in your blood — red cells, white cells, and platelets.",
    meaning_mr: "एक रक्त तपासणी जी तुमच्या रक्तातील पेशींची संख्या आणि प्रकार मोजते — लाल पेशी, पांढऱ्या पेशी, आणि प्लेटलेट्स.",
    why_you_hear_en: "Ordered during routine checkups, to investigate fatigue, fever, bleeding, or to monitor treatment effects.",
    why_you_hear_mr: "नियमित तपासण्यांदरम्यान, थकवा, ताप, रक्तस्त्राव तपासण्यासाठी, किंवा उपचारांचे परिणाम निरीक्षणासाठी घेतली जाते.",
    general_info_en: "Abnormal counts can indicate anemia, infection, clotting issues, or other conditions. Results should be interpreted by a doctor in context of your health.",
    general_info_mr: "असामान्य गणना रक्तक्षय, संक्रमण, गुठ्याळणी समस्या, किंवा इतर स्थिती दर्शवू शकतात. निकाल तुमच्या आरोग्याच्या संदर्भात डॉक्टरांद्वारे ओळखले जावेत.",
    source_en: "Mayo Clinic, MedlinePlus",
    source_mr: "मेयो क्लिनिक, मेडलाईनप्लस",
    reviewed_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
]

export const DEMO_HEALTH_ALERTS: HealthAlert[] = [
  {
    id: "ha1", slug: "monsoon-malaria-advisory",
    title_en: "Monsoon Malaria Advisory — Yavatmal District",
    title_mr: "पावसाळा मलेरिया सल्ला — यवतमाळ जिल्हा",
    severity: "advisory",
    area_en: "Yavatmal District including Pandharkawda",
    area_mr: "पांढरकवडा सहित यवतमाळ जिल्हा",
    active_from: new Date(Date.now() - 5 * 86400000).toISOString(),
    active_until: new Date(Date.now() + 60 * 86400000).toISOString(),
    summary_en: "Increased malaria cases reported during monsoon season. Residents advised to use mosquito nets and eliminate stagnant water.",
    summary_mr: "पावसाळ्यादरम्यान मलेरियाच्या रुग्णांची संख्या वाढली आहे. रहिवाशांनी मच्छरदाणी वापरण्याची आणि ठिपक्यांमधील पाणी काढण्याची जाहीर जाहीर सूचना.",
    action_en: "Use mosquito repellents and nets. Eliminate stagnant water around homes. Visit a doctor promptly if you experience fever with chills.",
    action_mr: "मच्छरदाणी आणि रेपेलंट वापरा. घरभोवती तळे असलेले पाणी काढा. तापासह थंडी आल्यास त्वरित डॉक्टरांकडे जा.",
    source_en: "District Health Office, Yavatmal",
    source_mr: "जिल्हा आरोग्य कार्यालय, यवतमाळ",
    published_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    reviewed_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "ha2", slug: "vaccination-camp-notice",
    title_en: "Free Measles-Rubella Vaccination Camp at Civil Hospital",
    title_mr: "सिव्हिल हॉस्पिटलमध्ये मोफत गोवर-रुबेला लसीकरण शिबीर",
    severity: "informational",
    area_en: "Pandharkawda",
    area_mr: "पांढरकवडा",
    active_from: new Date(Date.now() - 1 * 86400000).toISOString(),
    active_until: new Date(Date.now() + 14 * 86400000).toISOString(),
    summary_en: "A free MR vaccination camp for children aged 9 months to 15 years is running at Pandharkawda Civil Hospital daily from 9 AM to 1 PM.",
    summary_mr: "9 महिन्यांचे ते 15 वर्षांच्या मुलांसाठी मोफत एमआर लसीकरण शिबीर पांढरकवडा सिव्हिल हॉस्पिटलमध्ये दररोज सकाळी 9 ते दुपारी 1 वाजेपर्यंत सुरू आहे.",
    action_en: "Bring children in the eligible age group with their vaccination card. The camp is free of charge.",
    action_mr: "पात्र वयोगटातील मुलांना त्यांच्या लसीकरण कार्डसह आणा. शिबीर मोफत आहे.",
    source_en: "Pandharkawda Civil Hospital",
    source_mr: "पांढरकवडा सिव्हिल हॉस्पिटल",
    published_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    reviewed_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "ha3", slug: "heat-advisory-summer",
    title_en: "Heat Wave Advisory — Stay Hydrated",
    title_mr: "ऊनझळ सल्ला — आर्द्रता राखा",
    severity: "important",
    area_en: "Yavatmal District",
    area_mr: "यवतमाळ जिल्हा",
    active_from: new Date(Date.now() - 10 * 86400000).toISOString(),
    active_until: new Date(Date.now() + 30 * 86400000).toISOString(),
    summary_en: "High temperatures expected. Risk of heat-related illness especially for elderly, children, and outdoor workers.",
    summary_mr: "उच्च तापमान अपेक्षित. विशेषतः वृद्ध, मुले, आणि बाहेर काम करणाऱ्यांना ऊनझळीचा धोका.",
    action_en: "Drink plenty of water. Avoid going out between 12 PM and 4 PM. Wear light, loose clothing. Seek medical help if experiencing dizziness, nausea, or extreme fatigue.",
    action_mr: "भरपूर पाणी प्या. दुपारी 12 ते 4 वाजेत बाहेर पडू नका. हलके, सैल कपडे घाला. चक्कर, मळमळ, किंवा अत्यंत थकवा आल्यास वैद्यकीय मदत घ्या.",
    source_en: "District Health Office, IMD",
    source_mr: "जिल्हा आरोग्य कार्यालय, आयएमडी",
    published_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    reviewed_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
]

export const DEMO_UPDATES: HealthUpdate[] = [
  {
    id: "u1",
    title_en: "Cardiology visit date changed to 17 September",
    title_mr: "हृदयरोग भेटीची तारीख 17 सप्टेंबरला बदलली",
    category_en: "Visiting Doctor Change",
    category_mr: "भेट देणारे डॉक्टर बदल",
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    source_en: "Pandharkawda Medical Centre",
    source_mr: "पांढरकवडा मेडिकल सेंटर",
    verified: true,
    summary_en: "Dr. Priya Sharma's next cardiology visit has been confirmed for 17 September instead of the previously scheduled date.",
    summary_mr: "डॉ. प्रिया शर्माची पुढची हृदयरोग भेट 17 सप्टेंबरला पुष्टीकृत करण्यात आली आहे, आधीच्या नियोजित तारखेऐवजी.",
  },
  {
    id: "u2",
    title_en: "Free eye checkup camp announced at Civil Hospital",
    title_mr: "सिव्हिल हॉस्पिटलमध्ये मोफत नेत्र तपासणी शिबीर जाहीर",
    category_en: "Hospital Notice",
    category_mr: "रुग्णालय सूचना",
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    source_en: "Pandharkawda Civil Hospital",
    source_mr: "पांढरकवडा सिव्हिल हॉस्पिटल",
    verified: true,
    summary_en: "A free eye checkup camp will be held every Saturday this month. Cataract screening included.",
    summary_mr: "या महिन्यात प्रत्येक शनिवारी मोफत नेत्र तपासणी शिबीर आयोजित केले जाईल. मोतीबिंदू तपासणी समाविष्ट.",
  },
  {
    id: "u3",
    title_en: "City Care Clinic schedule needs reconfirmation",
    title_mr: "सिटी केअर क्लिनिक वेळापत्रकाची पुन्हा खात्री करणे आवश्यक",
    category_en: "Freshness Notice",
    category_mr: "ताजेपणा सूचना",
    date: new Date(Date.now() - 7 * 86400000).toISOString(),
    source_en: "Arogya Verification Team",
    source_mr: "आरोग्य पडताळणी संघ",
    verified: false,
    summary_en: "City Care Clinic's schedule has not been reconfirmed in over two weeks. Please call before visiting.",
    summary_mr: "सिटी केअर क्लिनिकचे वेळापत्रक दोन आठवड्यांहून अधिक काळ पुन्हा पुष्टीकृत केले गेले नाही. भेट देण्यापूर्वी कृपया कॉल करा.",
  },
]

export const DEMO_SERVICES: Service[] = [
  { id: "sv1", name_en: "Outpatient Consultation", name_mr: "बाह्यरुग्ण सल्ला", category_en: "Consultation", category_mr: "सल्ला", facility_id: "f1" },
  { id: "sv2", name_en: "Emergency Services", name_mr: "आपत्कालीन सेवा", category_en: "Emergency", category_mr: "आपत्कालीन", facility_id: "f1" },
  { id: "sv3", name_en: "Maternity Care", name_mr: "प्रसूती काळजी", category_en: "Maternity", category_mr: "प्रसूती", facility_id: "f1" },
  { id: "sv4", name_en: "Immunization", name_mr: "लसीकरण", category_en: "Preventive", category_mr: "प्रतिबंधक", facility_id: "f1" },
  { id: "sv5", name_en: "X-Ray", name_mr: "एक्स-रे", category_en: "Diagnostics", category_mr: "निदान", facility_id: "f4" },
  { id: "sv6", name_en: "Ultrasound", name_mr: "अल्ट्रासाऊंड", category_en: "Diagnostics", category_mr: "निदान", facility_id: "f4" },
  { id: "sv7", name_en: "Blood Tests", name_mr: "रक्त तपासण्या", category_en: "Diagnostics", category_mr: "निदान", facility_id: "f4" },
]

export const DEMO_USER_REPORTS: UserReport[] = [
  {
    id: "ur1", entity_type: "facility", entity_id: "f3",
    reason: "Incorrect schedule", details: "The clinic seems to close earlier than listed on weekends.",
    status: "open", created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "ur2", entity_type: "doctor", entity_id: "d3",
    reason: "Wrong phone number", details: "Phone number is not reachable.",
    status: "investigating", created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "ur3", entity_type: "facility", entity_id: "f2",
    reason: "Other", details: "Pharmacy timings changed.",
    status: "resolved", created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
]

export const DEMO_VERIFICATION_RECORDS: VerificationRecord[] = [
  {
    id: "vr1", entity_type: "facility", entity_id: "f3", entity_name: "City Care Clinic",
    current_data: { phone: "0000000000", hours: "9 AM - 8 PM" },
    proposed_data: { phone: "0000000001", hours: "9 AM - 7 PM" },
    source: "User report", notes: "Phone number and hours reported as incorrect by a user.",
    status: "pending", created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "vr2", entity_type: "doctor", entity_id: "d7", entity_name: "Dr. Sandeep Bhagwat",
    current_data: { facility_id: "f3", specialty: "Dermatologist" },
    proposed_data: { facility_id: "f5", specialty: "Dermatologist" },
    source: "Doctor self-report", notes: "Doctor reports moving to Pandharkawda Medical Centre.",
    status: "pending", created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
]

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: "al1", admin_user: "admin@arogya.in", action: "UPDATE",
    entity_type: "visiting_session", entity_id: "v1",
    change_summary: "Confirmed visiting session for Dr. Priya Sharma on 17 Sep 2026",
    before_data: { status: "pending" }, after_data: { status: "confirmed", confirmed_at: new Date().toISOString() },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "al2", admin_user: "admin@arogya.in", action: "CREATE",
    entity_type: "health_alert", entity_id: "ha2",
    change_summary: "Published new informational alert: MR Vaccination Camp",
    before_data: null, after_data: { title: "Free Measles-Rubella Vaccination Camp" },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "al3", admin_user: "editor@arogya.in", action: "UPDATE",
    entity_type: "doctor", entity_id: "d1",
    change_summary: "Updated last_verified timestamp for Dr. Anil Deshmukh",
    before_data: { last_verified: new Date(Date.now() - 10 * 86400000).toISOString() },
    after_data: { last_verified: new Date(Date.now() - 2 * 86400000).toISOString() },
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
]

export const DEMO_ADMIN_USERS: AdminUser[] = [
  { id: "au1", email: "admin@arogya.in", name: "System Administrator", role: "admin", created_at: new Date().toISOString() },
  { id: "au2", email: "editor@arogya.in", name: "Content Editor", role: "editor", created_at: new Date().toISOString() },
  { id: "au3", email: "viewer@arogya.in", name: "Read Only User", role: "viewer", created_at: new Date().toISOString() },
]
